#!/usr/bin/env python3
"""Generate the four-tool activation probe set from the existing eval scenarios.

Each skill's eval.yaml already encodes what should route to it (expect_activation:
true) and what should route elsewhere (expect_activation: false, an anti-trigger).
Those prompts are exactly the inputs an activation matrix needs, so we derive the
probe set from them instead of inventing new prompts — one positive and one
anti-trigger per skill (when available).

Output: eng/activation/probes.yaml — a flat list a human (or a driver) runs against
each installed tool, recording which skill actually activated.

Run: python3 eng/activation/generate_probes.py
"""
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required (pip install -r requirements.txt)", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent.parent
TESTS = ROOT / "tests"
OUT = ROOT / "eng" / "activation" / "probes.yaml"


def first(scenarios, want_activation):
    for sc in scenarios:
        if bool(sc.get("expect_activation")) == want_activation:
            return sc
    return None


def main():
    probes = []
    for eval_path in sorted(TESTS.glob("*/*/eval.yaml")):
        plugin, skill = eval_path.parent.parent.name, eval_path.parent.name
        data = yaml.safe_load(eval_path.read_text(encoding="utf-8")) or {}
        scenarios = data.get("scenarios", [])

        pos = first(scenarios, True)
        if pos:
            probes.append({
                "plugin": plugin,
                "prompt": pos["prompt"].strip(),
                "expect": "activate",
                "expected_skill": skill,
            })

        anti = first(scenarios, False)
        if anti:
            probes.append({
                "plugin": plugin,
                "prompt": anti["prompt"].strip(),
                "expect": "not-activate",
                "expected_skill": skill,   # this skill must NOT be the one that activates
                "note": anti.get("name", ""),
            })

    OUT.write_text(
        "# Generated by eng/activation/generate_probes.py — do not hand-edit.\n"
        "# One positive + one anti-trigger probe per skill, drawn from tests/**/eval.yaml.\n"
        "# 'activate' = expected_skill SHOULD be selected; 'not-activate' = it must NOT be.\n"
        + yaml.safe_dump({"probes": probes}, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )
    pos = sum(1 for p in probes if p["expect"] == "activate")
    neg = len(probes) - pos
    print(f"generate_probes.py: wrote {len(probes)} probes ({pos} activate, {neg} not-activate) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
